name: gpa_calcos
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  flutter_gemini: ^2.0.3
  carousel_slider: ^4.0.0

  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  auto_route: ^8.1.3
  google_mlkit_image_labeling: ^0.12.0
  image_picker: ^1.0.8
  dash_chat_2: ^0.0.20
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  fluttertoast: ^8.2.5
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_calendar: ^25.2.6+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
dev_dependencies: 
  auto_route_generator: ^8.0.0
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0

flutter_icons:  # Correct typos and indentation
    android: true    
    ios: true
    image_path: "try.png"  # Replace with the actual path to your icon 
    web:
      generate: true
      image_path: "try.png"
      background_color: "#ffffff"
      theme_color: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - assets/


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
